### ISSUE TITLE
"The job has no provider assigned" when submitting a job from the TMGMT/sources page.

### ISSUE THREAD

**Issue by heartdriven** [openeuropa/oe_translation#116]
# Description
On the culture site we have issues submitting a translation.  We get an error upon submission from the translation overview page (admin/tmgmt/sources).  I have been able to reproduce this on a clean install.

After inspecting and catching the error in the code, I see that the job has no provider assigned and this is why the error is thrown.  So I think there is something that goes wrong when requesting the translation.

Thanks for looking into this!

# Steps to reproduce
- Check out this repository and spin up and install a local drupal instance
- Create a basic page
- Access "admin/tmgmt/sources" and check the box next to the newly created page.
- Click "Request translation" button
- Error happens, stack trace here:

```The website encountered an unexpected error. Please try again later.

Drupal\tmgmt\TMGMTException: The job has no provider assigned. in Drupal\tmgmt\Entity\Job->getTranslator() (line 525 of modules/contrib/tmgmt/src/Entity/Job.php).
Drupal\tmgmt\Entity\Job->getTranslatorPlugin() (Line: 26)
Drupal\oe_translation\Access\JobAccessHandler->checkAccess(Object, 'submit', Object) (Line: 105)
Drupal\Core\Entity\EntityAccessControlHandler->access(Object, 'submit', Object, ) (Line: 709)
Drupal\Core\Entity\ContentEntityBase->access('submit') (Line: 159)
Drupal\tmgmt\JobCheckoutManager->checkoutMultiple(Array) (Line: 69)
Drupal\tmgmt\JobCheckoutManager->checkoutAndRedirect(Object, Array) (Line: 173)
Drupal\tmgmt\SourcePluginUiBase->overviewFormSubmit(Array, Object, 'node') (Line: 254)
Drupal\tmgmt\Form\SourceOverviewForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('tmgmt_overview_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)```

**Comment by upchuk** [comment]
@heartdriven I believe you are misusing the module. Thats not how you are supposed to translate. Once a node type is translatable, go to the node, click the translate tab and then you'll have the button to tranbslate locally. You do not use `Request translation` for local translation.

**Comment by heartdriven** [comment]
@upchuk thanks for your quick response.

We use the poetry connector as a provider, not local translations.  In the example above, the use the mock provider is used (enabled by default in this installation).  The issue i'm describing here is identical on the d8 culture site.

**Comment by upchuk** [comment]
@heartdriven OK, regardless. You do not make translations by going to `admin/tmgmt/sources`. It's always by going to the node Translate tab. If poetry is configured correctly, you will see the checkboxes and the Request button at the top.

**Comment by nicocasel** [comment]
If I am correct, @upchuk  is talking about this interface:
![dgt translations](https://user-images.githubusercontent.com/5740059/100436567-d1a33700-309f-11eb-85ae-1b6a293a240d.png)

Once "Request a DGT translation for the selected languages" has been clicked, it creates a 'job', which is visible in the TMGMT Job Items list ( /admin/tmgmt/job_items_en )

**Comment by heartdriven** [comment]
Yes, indeed.  If this is the suggested workflow, we will follow that of course.  However, it is possible to circumvent this workflow and submit translations via the tmgmt interface, causing the job items overview to break (See the error report above).

So maybe we could implement a way to disable submissions using the overview?  In my experience, I see users submitting this the wrong way, even though we documented otherwise...

**Comment by upchuk** [comment]
Yeah, it should be submitted like that. But it's just a matter of permissions. If i remember correctly, this can be prevented. We don't have this issue of users using the TMGMT interface for submitting translations.

**Comment by brummbar** [comment]
Closing as it's permission related.
