### ISSUE TITLE
Route "view.tmgmt_translation_all_job_items.page_1" does not exist

### ISSUE THREAD

**Issue by dhamaris** [openeuropa/oe_translation#180]
**Description:** 
- Drupal 9.4.1 
- PHP/7.4.21. 
- Apache Server.

**Stepts to reproduce:**
I installed the following modules related to translation:
![image](https://user-images.githubusercontent.com/1392485/193070131-f77a7b8f-460f-4c01-a0d6-64e62f7d16bb.png)

When accessing to both providers and settings:
![image](https://user-images.githubusercontent.com/1392485/193070362-e25932ca-193f-42ea-b3ef-fc654fd0aede.png)

I get this error:
`Symfony\Component\Routing\Exception\RouteNotFoundException: Route "view.tmgmt_translation_all_job_items.page_1" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of core\lib\Drupal\Core\Routing\RouteProvider.php).
`
I checked the documentation and I am not sure of whether there is something missing. Can you please help me?

Thank you

**Comment by brummbar** [comment]
This view was coming from tmgmt itself: https://git.drupalcode.org/project/tmgmt/-/blob/8.x-1.11/config/install/views.view.tmgmt_translation_all_job_items.yml?ref_type=tags .
