### ISSUE TITLE
Dependency to older version of tmgmt module

### ISSUE THREAD

**Issue by dhamaris** [openeuropa/oe_translation#185]
Hello, I am using version 1.14 of translation management tool module: https://www.drupal.org/project/tmgmt as older versions contain bugs, but oe_translation module has a dependency to 1.11 version. 
Are you maintaining oe_translation module?

![image](https://user-images.githubusercontent.com/1392485/202747654-5d7953b1-566e-4817-b807-a30b7298df8c.png)

**Comment by brummbar** [comment]
Hello @dhamaris , newer versions of tmgmt introduced changes that were not compatible anymore with the needs of oe_translation, so we had to lock the version to 1.11.
Apologies for the delayed response.
