### ISSUE TITLE
Version conflict with guzzle and core-recommended

### ISSUE THREAD

**Issue by donquixote** [openeuropa/oe_translation#244]
I created a composer.json with this minimal dependencies list:
```json
    "require": {
        "openeuropa/oe_translation": "^2",
        "drupal/core-recommended": "^9.5"
    },
```

On install I get this:

>   Problem 1
>     - Root composer.json requires openeuropa/oe_translation ^2 -> satisfiable by openeuropa/oe_translation[2.0.0-alpha1, 2.x-dev].
>     - drupal/core-recommended[9.5.0-beta1, ..., 9.5.x-dev] require guzzlehttp/guzzle ~6.5.8 -> satisfiable by guzzlehttp/guzzle[6.5.8, 6.5.x-dev].
>     - Conclusion: don't install guzzlehttp/guzzle 6.5.8 (conflict analysis result)
>     - Root composer.json requires drupal/core-recommended ^9.5 -> satisfiable by drupal/core-recommended[9.5.0-beta1, ..., 9.5.x-dev].

The problem is that core-recommended requires a specific version of guzzle.

Should oe_translation add support for guzzle 6?
Or is there a trick to ignore some dependencies in core-recommended? Drupal core itself allows guzzle 7.

**Comment by donquixote** [comment]
> Or is there a trick to ignore some dependencies in core-recommended? Drupal core itself allows guzzle 7.

This works:
```json
    "require": {
        "guzzlehttp/guzzle": "7.5.1 as 6.5.8",
        "drupal/core-recommended": "^9.5",
        "openeuropa/oe_translation": "^2"
    },
```

I don't really like the super specific versions required for `* as *` syntax.

**Comment by upchuk** [comment]
@donquixote Hey there. No alternative. drupal/core-recommended is very annoying in this case and locks us into this thing. Until D10, we will have to do this unfortunately.
