### ISSUE TITLE
Warning: Undefined array key "#value" in Drupal\oe_translation\Form\TranslationRequestForm::validateMaxLength() (line 50 of /oe_translation/src/Form/TranslationRequestForm.php)

### ISSUE THREAD

**Issue by mario-prkos** [openeuropa/oe_translation#248]
Here:
https://github.com/openeuropa/oe_translation/blob/52c860f7f936a225146e351147cd975190bac0f9/src/Form/TranslationRequestForm.php#L49
mb_strlen($element['#value']) get empty value, The cause comes from text_format field type which has different array structure. It doesn't have element['#value'] but element['value'] and inside that array has element['value']['#value].

"#type" => "text_format"
  "#default_value" => "<p>Do you want to read more questions and answers?</p>"
  "#title" => Drupal\Core\StringTranslation\TranslatableMarkup {[#2231 ▶]
  "#rows" => 3
  "#allow_focus" => false
  "#disabled" => true
  "#max_length" => 255
  "#element_validate" => array:1 [▶]
  "#allowed_formats" => array:1 [▶]
  "#process" => array:3 [▶]
  "#base_type" => "textarea"
  "#theme_wrappers" => array:1 [▶]
  "#pre_render" => array:3 [▶]
  "#defaults_loaded" => true
  "#tree" => true
  "#parents" => array:2 [▶]
  "#array_parents" => array:4 [▶]
  "#weight" => 0.001
  "#processed" => true
  "#required" => false
  "#attributes" => array:1 [▶]
  "#title_display" => "before"
  "#description_display" => "after"
  "#errors" => null
  "#id" => "..."
  "value" => array:36 [▼
    "#type" => "textarea"
    "#default_value" => "<p>Do you want to read more questions and answers?</p>"
    "#title" => Drupal\Core\StringTranslation\TranslatableMarkup {[#2231 ▶]
    "#rows" => 3
    "#allow_focus" => false
    "#disabled" => true
    "#max_length" => 255
    "#element_validate" => array:1 [▶]
    "#allowed_formats" => array:1 [▶]
    "#base_type" => "textarea"
    "#defaults_loaded" => true
    "#tree" => true
    "#array_parents" => array:5 [▶]
    "#required" => false
    "#attributes" => array:2 [▶]
    "#title_display" => "before"
    "#description_display" => "after"
    "#errors" => null
    "#input" => true
    "#cols" => 60
    "#resizable" => "vertical"
    "#process" => array:3 [▶]
    "#pre_render" => array:1 [▶]
    "#theme" => "textarea"
    "#theme_wrappers" => array:1 [▶]
    "#value_callback" => array:2 [▶]
    "#parents" => array:3 [▶]
    "#weight" => 0
    "#processed" => true
    "#value" => "<p>Do you want to read more questions and answers?</p>"
    "#ajax_processed" => false
    "#groups" =>[▶]
    "#sorted" => true
    "#validated" => true
  ]
Also it will be good to put check up if $element['#value'] is empty.

**Comment by upchuk** [comment]
Thank you, will be fixed in https://github.com/openeuropa/oe_translation/pull/247
