### ISSUE TITLE
Cannot apply patch stop_propagation

### ISSUE THREAD

**Issue by AGonzaNu** [openeuropa/oe_translation#279]
Hi,
I'm upgrading drupal core from 9.5.11 to 10.1.5 and I'm getting an error when applying the stop_propagation patch of oe_translation v2.3.0 [https://github.com/openeuropa/oe_translation/blob/2.x/composer.json#L86](https://github.com/openeuropa/oe_translation/blob/2.x/composer.json#L86)
![image](https://github.com/openeuropa/oe_translation/assets/90603544/f99cff36-bade-4464-9843-b9911d0c08fb)
I propose to regenerate the patch if necessary or remove it if it is not necessary.
King regards.
Antonio

**Comment by brummbar** [comment]
Hello, this is already indicated in the README: https://github.com/openeuropa/oe_translation#usage-with-drupal-10
